name: Deploy Storybook to GitHub Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Test and Lint'
    branches:
      - main
    types:
      - completed

concurrency:
  group: storybook-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Setup Node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # renovate: tag=v3
        with:
          node-version-file: '.tool-versions'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install-ci

      - name: Build storybook
        run: yarn build-storybook

      - name: Upload storybook
        uses: actions/upload-pages-artifact@64bcae551a7b18bcb9a09042ddf1960979799187 # renovate: tag=v1
        with:
          path: ./storybook-static

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.pages_deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy storybook
        id: pages_deployment
        uses: actions/deploy-pages@af48cf94a42f2c634308b1c9dc0151830b6f190a # renovate: tag=v2
